#management:
#  server:
#    port: 8666 #管理端口调整成8666
#    address: 127.0.0.1
#    servlet:
#      context-path: /monitor #actuator的访问路径
#  endpoint:
#    shutdown:
#      enabled: true
spring:
  profiles: daily

  data:
    jest:
      uri: http://es-sg-pqo0r6ozr0001bvcm.elasticsearch.aliyuncs.com:9200
  redis:
    database: 0
    host: r-1uda8facb9e960e4.redis.rds.aliyuncs.com
    password: Injoin123
    port: 6379
    timeout: 3000
    pool:
      max-idle: 500 # 连接池中的最大空闲连接，默认值也是8。
      min-idle: 50 #连接池中的最小空闲连接，默认值也是0。
      max-active: 2000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException

tablestore:
  product: tablestore
  region: cn-hangzhou
  endpoint: https://injoin-daily.cn-hangzhou.ots.aliyuncs.com
  instance:
    name: injoin-daily

yunxin:
  appKey: c62fb60e44516af6974004b99ce93093
  appSecret: d06841aa9f4a
  createAccIdUrl: https://api.netease.im/nimserver/user/create.action