spring:
  profiles: pre

  data:
    jest:
      uri: http://es-sg-25u0tg0xx0003oitb.elasticsearch.aliyuncs.com:9200
      username: elastic
  redis:
    database: 0
    host: r-6gj01f4a9d22cfc4.redis.ap-south-1.rds.aliyuncs.com
    port: 6379
    timeout: 3000
    pool:
      max-idle: 500 # 连接池中的最大空闲连接，默认值也是8。
      min-idle: 50 #连接池中的最小空闲连接，默认值也是0。
      max-active: 2000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
  datasource:
    url: jdbc:mysql://rm-6gj2j56ifgq7nuxqz.mysql.ap-south-1.rds.aliyuncs.com:3306/ijboss?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: tsa
    password: tsa^togetU
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

tablestore:
  product: tablestore
  region: ap-south-1
  endpoint: http://injoin-injoin-online.ap-south-1.vpc.ots.aliyuncs.com
  instance:
    name: injoin-online

yunxin:
  createAccIdUrl: https://api.netease.im/nimserver/user/create.action

address:
  api:
    tsuser:
      user: http://192.168.9.79:8013/accounts